##################################################
#          Thanks for downloading WCNP!          #
#                                                #
#               WCNP version: 0.1.8              #
#            Plugin coded by Geka                #
##################################################

#######################################################################################

# Here you can change the message that appears in the FIRST line in the message.
# Supports color codes! 
# IMPORTANT: If you put a message with ', make sure to put 2.
# Example: 
    # BAD: You don't have permission to do this.
    # GOOD: You don''t have permission to do this.
    # And it will appear like: You don't have permission to do this. :)
Line1: '  &6&lMmm... No, you can''t do that!'

#######################################################################################

# Here you can change the message that appears in the SECOND line in the message.
# Suports color codes!
# REMEMBER! If you put a message with ', make sure to put 2.
# Example: 
    # BAD: You don't have permission to do this.
    # GOOD: You don''t have permission to do this.
    # And it will appear like: You don't have permission to do this. :)
Line2: '    &6&lThat''s ilegal :P'

#######################################################################################

# Here, you can edit the color of the smiley/face.
# If you don't understand it, please contact me (admin@zekatis.co).
# IMPORTANT: Do not erase the #!!! Only change the & 4 (color)
# Suports color codes!
Face1: '&a########'
Face2: '&a##&0#&a##&0#&a##'
Face3: '&a##&0#&a##&0#&a##'
Face4: '&a########'
Face5: '&a##&0####&a##'
Face6: '&a#&0#&a####&0#&a#'
Face7: '&a#&0#&a####&0#&a#'
Face8: '&a########'

#######################################################################################

#  Here you can add your custom commands!
# Do not write them with the /, only write the word for the command.
# Example:
    # BlockedCommands:
       # -'/plugins' ---->> BAD!
       # -'plugins' ----->> GOOD!
# Feel free to add all the commands you want.

# For ADMINISTRATORS/STAFF, you can bypass this adding the permission
# "wcnp.bypass" in the config.yml from your BungeeCord server.

BlockedCommands:
  - 'pl'
  - '?'
  - 'plugins'
  - 'bukkit:plugins'
  - 'bukkit:?'
  - 'bukkit:pl'
  
########################################################
# If you need any help with the plugin, please         #
# contact me on Spigot or via Email: hello@gekatik.com #
########################################################
